name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: axial-camp-377809

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover

    - name: Build Docker image
      run: docker build -t myapp:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker tag myapp:latest ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11

    - name: Run terraform plan
      run: |
        echo 'terraform {
          required_providers {
            google = {
              source = "hashicorp/google"
              version = ">= 3.0"
            }
          }
        }
        provider "google" {
          credentials = "${{ secrets.TF_GOOGLE_CREDENTIALS }}"
          project     = "${{ env.GCP_PROJECT_ID }}"
          region      = "us-central1"
        }' > ./terraform/main.tf
        cat ./terraform/main.tf
        terraform init -input=false -backend=false
        terraform plan -input=false -var "gcp_credentials=${{ secrets.TF_GOOGLE_CREDENTIALS }}" -var "gcp_project_id=${{ env.GCP_PROJECT_ID }}"
