name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Docker
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Container Registry
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/axial-camp-377809/dareit-challenge:${{ github.sha }}

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: axial-camp-377809
        service_account_key: ${{ secrets.GCR_JSON_KEY }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init and Apply
      run: |
        echo "gcp_credentials = \"${{ secrets.TF_GOOGLE_CREDENTIALS }}\"" > terraform.tfvars
        echo "gcp_project_id = \"axial-camp-377809\"" >> terraform.tfvars
        terraform init
        terraform apply -auto-approve

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials/dareit-challenge-cluster --zone us-central1-a
        kubectl apply -f k8s-deployment.yaml
        kubectl set image deployment/dareit-challenge/dareit-challenge=gcr.io/axial-camp-377809/dareit-challenge:${{ github.sha }}
